Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -80,10 +80,45 @@ jobs:
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
+            NEW_IMAGE=${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
+
+            echo "Getting current running container..."
+            OLD_CONTAINER=$(docker ps --filter "name=myapp" --format "{{.ID}}")
+            OLD_IMAGE=$(docker inspect --format='{{.Config.Image}}' $OLD_CONTAINER || true)
+
+            echo "Old image: $OLD_IMAGE"
+
+            echo "Pull new image"
+            docker pull $NEW_IMAGE
+
+            echo "Stop and remove old container"
             docker stop myapp || true
             docker rm myapp || true
-            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
-            docker run -d -p 8000:8000 --name myapp ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
+
+            echo "Run new container"
+            docker run -d -p 8000:8000 --name myapp $NEW_IMAGE
+
+            echo "Waiting for app..."
             sleep 5
-            curl -f http://localhost:8000 || exit 1
-            docker image prune -af
+
+            echo "Health check..."
+            if curl -f http://localhost:8000/health; then
+              echo "Deployment successful ✅"
+            else
+              echo "Deployment failed ❌ → rolling back..."
+
+              docker stop myapp || true
+              docker rm myapp || true
+
+            if [ ! -z "$OLD_IMAGE" ]; then
+              echo "Restoring old image..."
+              docker run -d -p 8000:8000 --name myapp $OLD_IMAGE
+              echo "Rollback completed 🔁"
+            else
+              echo "No previous image found!"
+            fi
+
+            exit 1
+            fi
+
+  docker image prune -af
